version: '3.4'

services:
  api-service:
    # build: 
    #   context: .
    #   dockerfile: dockerfile
    image: ejkonge/api
    volumes:
      - ~/app:/app
    ports:
      - 8080:8080
    restart: always